### ISSUE TITLE
issue in balance.js

### ISSUE THREAD

**Issue by korrykatti** [Koolwiza/Bot-12#31]
let user = await client.resolveUser(args[0]) ?? message.author
                                                  ^

SyntaxError: Unexpected token '?'

**Comment by Koolwiza** [comment]
Update your node to v12+

**Comment by korrykatti** [comment]
it is

**Comment by Koolwiza** [comment]
Do `node -v` in terminal

**Comment by korrykatti** [comment]
12

**Comment by Koolwiza** [comment]
Can you show more code?

**Comment by korrykatti** [comment]
what do you mean ?

**Comment by Koolwiza** [comment]
Uh show relevant code

**Comment by whirlxd** [comment]
lol you need node v14+ 
@Koolwiza @korrykatti
